create table Transactions(
    Transaction_id     integer generated by default as identity primary key,
    account_number     number ,
    amount             number,
    transaction_type   varchar2(50),
    execution_date     date,
    status             varchar2(10) not null,
    currency           varchar2(3) not null,
    batch_id           integer,
    CREATED_at         date default sysdate,
    constraint fk_batch foreign key (batch_id) references batch(batch_id),
    constraint chk_valid_currency check (UPPER(currency) in ('MAD','USD','GBP','KWD','CHF','CAD','AUD','JPY','CNY')),
    constraint chk_valid_status check (UPPER(status) in ('VALID','INVALID'))

);