create table Transaction_errors(
    id                     integer generated by default as identity primary key,
    Transaction_id         integer not null,
    error_message          varchar2(250),
    error_code             varchar2(50) not null,
    error_type              varchar2(20) not null,
    constraint fk_transaction foreign key (Transaction_id) references transactions(Transaction_id),
    constraint chk_error_type check(upper(error_type) in ('BUSINESS','TECHNICAL'))
);