# Generated by Django 4.2.7 on 2025-12-22 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_transactions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_number', models.DecimalField(decimal_places=0, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(max_length=50)),
                ('execution_date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='core.batch')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionError',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('error_message', models.TextField()),
                ('error_code', models.CharField(max_length=50)),
                ('error_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='errors', to='core.transaction')),
            ],
        ),
    ]
